phone/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^operatoradmin/login/','operatoradmin.views.operatoradmin',name="operatoradmin"),
    url(r'^operatoradmin/profile/','operatoradmin.views.Profile',name="Profile"),
    url(r'^logout/$', 'operatoradmin.views.logout_view',name='logout_page'),
    url(r'^vendor/','operatoradmin.views.vendor_login',name="vendor"),
    url(r'^adduser/','operatoradmin.views.AddUser',name="vendor"),
    url(r'^editprofileinfo/(?P<user_id>\d+)/','operatoradmin.views.editprofilecinfo',name="editprofilecinfo"),
    url(r'^deleteuserinfo/(?P<id>\d+)/','operatoradmin.views.deleteuserinfo',name="deleteuserinfo"),
    url(r'^category/','operatoradmin.views.Categories',name="Categories"),
    url(r'^subcategory/','operatoradmin.views.Sub_Category',name="SubCategory"),
    url(r'^brand/','operatoradmin.views.brand',name="brand"),
    url(r'^show/','operatoradmin.views.show',name="brand"),
    url(r'^get_product_list/','operatoradmin.views.vendor_get_product_list',name="vendor_get_product_list"),
    url(r'^editproductinfo/(?P<user_id>\d+)','operatoradmin.views.edit_produt_info',name="edit_produt_info"),
    url(r'^deleteproductinfo/(?P<id>\d+)/','operatoradmin.views.delete_product_info',name="delete_product_info"),
    url(r'^changepassword/','operatoradmin.views.change_password',name="change_password"),
    #url(r'^list','operatoradmin.views.listing',name="change_password"),
    url(r'^category_id/(?P<cat_id>\d+)/','operatoradmin.views.vendor_category',name="vendor_category"),
    url(r'^subcategory_id/(?P<cat_id>\d+)/','operatoradmin.views.vendor_subcategory',name="vendor_subcategory"),
    url(r'^product_image/(?P<id>\d+)/','operatoradmin.views.product_image',name="vendor_subcategory"),
    url(r'^facebook/$', 'operatoradmin.views.facebook', name='home'),
    url(r'^home/$', 'operatoradmin.views.home', name='home'),
    #url(r'^comments/', include('django.contrib.comments.urls')


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

operatoradmin/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db import IntegrityError
from django_comments.models import Comment
# Create your models here.
class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    user_type = models.CharField(max_length=25, blank=True, null=True,default="vendor",help_text="saikrishna")
    #user_type = models.CharField(max_length=25, blank=True, null=True,default="vendor",help_text="All dummies should have names right?")

    def __unicode__(self):
        return u'%s' % (self.user)


class Category(models.Model):
    #user = models.ForeignKey(User, unique=True)
    parent_id = models.IntegerField(default=0)
    category_name = models.CharField(max_length=45, blank=True, null=True)
    #user_id=models.IntegerField()
    def __unicode__(self):
        return "%s" % self.category_name

class Brand(models.Model):
    brand_name = models.CharField(max_length=45, blank=True, null=True)
    category = models.ForeignKey(Category)
    def __unicode__(self):
        return "%s" % self.brand_name


class Vendor(models.Model):
    category_name=models.CharField(max_length=45, blank=True, null=True)
    sub_category_name=models.CharField(max_length=45, blank=True, null=True)
    brand_name=models.CharField(max_length=45, blank=True, null=True)
    user_name=models.CharField(max_length=45, blank=True, null=True)
    product_name=models.CharField(max_length=45, blank=True, null=True)
    description=models.TextField(max_length=1000)
    image1 =models.ImageField(upload_to="image/")
    image2=models.ImageField(upload_to="image/")
    image3=models.ImageField(upload_to="image/")
   
  
  

operatoradmin/forms.py
from django import forms
from django.contrib.auth.models import User
from models import UserProfile,Category,Vendor,Brand
from django.core import validators


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = "__all__"


class CategoryForm(forms.Form):

    #parent_id=forms.IntegerField()
    category_name=forms.CharField(max_length=30, min_length=4)
    #user_id=forms.IntegerField()
    def clean_category_name(self):
            u = self.cleaned_data['category_name']
            print u
            if not Category.objects.filter(category_name = u):
                return u
            else:
                raise forms.ValidationError("category name is already exists")

class SubCategoryForm(forms.Form):
    category_id=forms.ModelChoiceField(queryset=Category.objects.all().order_by('category_name')) 
    category_name=forms.CharField(max_length=30, min_length=4)
    #user_id=forms.IntegerField()
    '''def clean_sub_category_name(self):
            u = self.cleaned_data['sub_category_name']
            print u
            if not SubCategory.objects.filter(sub_category_name = u):
                return u
            else:
                raise forms.ValidationError("subcategory name is already exists")'''


class BrandForm(forms.Form):

    category_id=forms.ModelChoiceField(queryset=Category.objects.all().order_by('category_name'))
    brand_name=forms.CharField(max_length=30, min_length=4)

#class TestForm(forms.Form):
        #user_type=forms.CharField(max_length=30, min_length=4)




class VendorForm(forms.Form):
    
    category_name=forms.ModelChoiceField(queryset=Category.objects.all().order_by('category_name'))
    #category_name=forms.ModelChoiceField(queryset=Category.objects.filter(category_name=category_name).order_by('category_name'))
    subcategory_name=forms.ModelChoiceField(queryset=Category.objects.all().order_by('parent_id'))
    brand_name=forms.ModelChoiceField(queryset=Brand.objects.all().order_by('brand_name'))
    user_name=forms.CharField(max_length=30, min_length=4)
    product_name=forms.CharField(max_length=30, min_length=4)
    description=forms.CharField(widget=forms.Textarea(attrs={'cols': 80, 'rows': 20}))
    image1 = forms.ImageField()
    image2=forms.ImageField()
    image3=forms.ImageField()
    

operatoradmin/views.py
from django.shortcuts import render
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import logout
from models import UserProfile,Category,Vendor,Brand
from forms import CategoryForm,VendorForm,SubCategoryForm,BrandForm
#from forms import TestForm
from django import forms
import pdb
import json, pdb, hashlib
from django.contrib import auth

from django.contrib.auth.hashers import *

from django.shortcuts import render
# Create your views here.i
from django.http import HttpResponseRedirect,HttpResponse
import requests
from facebook import FacebookAPI
from facebook import GraphAPI
from django.shortcuts import render
import pdb
import urllib
import json

"""This funtion login for admin and vendor 
   checking credentials"""

def operatoradmin(request):
    if request.method == "POST":
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username = username, password = password)
        if user:
            try:
                res = UserProfile.objects.get(user_id = user.id)
                role = res.user_type
                if role == "admin":
                    if user is not None and user.is_active:
                        auth.login(request, user)
                        return HttpResponseRedirect("/operatoradmin/profile/")
                else:
                    if user is not None and user.is_active:
                        auth.login(request, user)
                        return HttpResponseRedirect("/vendor/")
                    else:
                        error = "yes"
                        return render(request,"login.html",locals())
            except:
                return HttpResponse("Role is not defind")
        else:
            error = "yes"
            return render(request,"login.html",locals())
    return render(request, "login.html", locals())


""" admin profile function"""

@login_required(login_url='/operatoradmin/login/')

def Profile(request):
 
    user = User.objects.filter(is_superuser = False)
    if user:
        success="yes"
        return render(request, "profile.html", locals())
    else:
        return render(request, "profile.html", locals())

"""vendor login funtion"""

def vendor_login(request):
    current_user = request.user
    print current_user
    category_list= Category.objects.all()
    brand_list=    Brand.objects.all()
    print brand_list
    if request.method=="POST":
        form = VendorForm(request.POST,request.FILES)
        if form.is_valid():
            category_name = form.cleaned_data['category_name']
            sub_category_name=form.cleaned_data['category_name']
            user_name=form.cleaned_data['user_name']
            brand_name=form.cleaned_data['brand_name']
            product_name=form.cleaned_data['product_name']
            description=form.cleaned_data['description']
            image1=form.cleaned_data['image1']
            image2=form.cleaned_data['image2']
            image3=form.cleaned_data['image3']
            v=Vendor()
            v.category_name=category_name
            v.sub_category_name=sub_category_name
            v.brand_name=brand_name
            v.user_name=user_name
            v.product_name=product_name
            v.description=description
            v.image1=image1
            v.image2=image2
            v.image3=image3
            v.save()
            success="yes"
            return render(request,"product_add_info.html",locals())
        else:
            return HttpResponse(form.errors)
    else:
            form = VendorForm()

    return render(request, "vendor.html", locals())

"""admin logout fucntion"""

def logout_view(request):

    logout(request)
    # Redirect to a success page.
    return HttpResponseRedirect("/operatoradmin/login/")

"""validate the user"""

def validation(data):
    username = data.get("username", None)
    try:
        user = User.objects.get(username__iexact = username)
        return False
    except User.DoesNotExist:
        return True

"""Admin add user function"""

@login_required(login_url='/operatoradmin/login/')

def AddUser(request):
    if request.method == 'POST':
        print validation(request.POST)
        if validation(request.POST):
            username = request.POST.get("username", None)
            password = request.POST.get("password", None)
            email = request.POST.get("email", None)
            print username, password, email
            user = User.objects.create_user(username = username,\
                   password = password, email = email)
            up = UserProfile()
            up.user=user
            up.save()
            success = "yes"
            # Redirect to a register page.
            return render(request,"register.html",locals())
        else:
            error = "yes"
            return HttpResponse("USER ALREDAY EXIST")
    return render(request,"register.html",locals())

"""user edit fucntion"""

@login_required(login_url='/operatoradmin/login/')

def editprofilecinfo(request, user_id):
    if request.method == "POST":
        try:
            user = User.objects.get(pk = user_id)
            user.username = request.POST.get("username", None)
            user.email = request.POST.get("email", None)
            user.save()
            return HttpResponseRedirect("/operatoradmin/profile/")

        except:
            return HttpResponse("unable to add user")
    return render(request, "editprofileinfo.html", locals())

"""user delete funtion """

@login_required(login_url='/operatoradmin/login/')

def deleteuserinfo(request, id):
    try:
        user_delete = User.objects.get(pk = id).delete()
    except:
        return HttpReponse("unable delete user")
    return HttpResponseRedirect("/operatoradmin/profile/")

""" This funtion can does 
    To add catagories list"""

@login_required(login_url='/operatoradmin/login/')

def Categories(request):
    current_user = request.user
    print current_user.id
    if request.method=="POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            category_name = form.cleaned_data['category_name']
            if category_name and Category.objects.filter(category_name=category_name).exists():
                  raise forms.ValidationError('This category name already exists as an account.')
            else:
                c = Category()
                c.category_name = category_name
                c.save()
                success="yes"
                return render(request, "category.html", locals())
    else:
            form = CategoryForm()
    return render(request, "category.html", locals())
  
""" This function can do as add subcategiry"""

@login_required(login_url='/operatoradmin/login/')

def Sub_Category(request):
    current_user = request.user
    category=Category.objects.all()
    if request.method=="POST":
        form = SubCategoryForm(request.POST)
        if form.is_valid():
            category_name = form.cleaned_data['category_name']
            category_id=form.cleaned_data['category_id']
            c = Category()
            c.category_name = category_name
            c.parent_id=category_id.id
            c.save()
            success="yes"
            return render(request, "subcategory.html", locals())
        else:
            return HttpResponse(form.errors)
    else:
            form = SubCategoryForm()
    return render(request, "subcategory.html", locals())

""" Tjhsi function can do as add brand """

@login_required(login_url='/operatoradmin/login/')

def brand(request):
    if request.method=="POST":
        form = BrandForm(request.POST)
        if form.is_valid():
            brand_name = form.cleaned_data['brand_name']
            category_id=form.cleaned_data['category_id']
            c = Brand()
            c.brand_name = brand_name
            c.category_id=category_id.id
            c.save()
            success="yes"
            return render(request, "brand.html",locals())
        else:
            return HttpResponse(form.errors)
    else:
        form = BrandForm()
    return render(request,"brand.html",locals())

   

def show(request):

     result=User.objects.all().order_by('username')
     return render(request,"show.html",locals()) 

""" this fucntion  can do as show all product list"""

@login_required(login_url='/operatoradmin/login/')

def vendor_get_product_list(request):
    user_name=request.user
    product_list=Vendor.objects.filter(user_name= user_name)

    return  render(request,"vendor_get_product_list.html",locals())

""" add product information """
@login_required(login_url='/operatoradmin/login/')

def edit_produt_info(request, user_id):
    if request.method == "POST":
        try:
            product_info = Vendor.objects.get(pk = user_id)
            product_info.category_name = request.POST.get("category_name", None)
            product_info.sub_category_name=request.POST.get("sub_category_name", None)
            product_info.brand_name= request.POST.get("brand_name" ,None)
            product_info.product_name= request.POST.get("product_name" ,  None)
            product_info.description= request.POST.get("description",None)
            product_info.save()
            success="yes"
            return HttpResponseRedirect("/get_product_list/")
        except:
            return HttpResponse("unable to edit ")
    return render(request, "editproductinfo.html", locals())

"""product  delete funtion """

@login_required(login_url='/operatoradmin/login/')

def delete_product_info(request, id):
    try:
        product_delete = Vendor.objects.get(pk = id).delete()
        success="yes"
    except:
        return HttpReponse("unable delete user")
        

operatoradmin/templates/backup_reg.html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>AMPM solutions</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="static/css/font-awesome.css" rel="stylesheet">
     <link href="/static/css/plugins/iCheck/custom.css" rel="stylesheet">
     <link href="/static/css/ampm.css" rel="stylesheet">



    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="static/css/style.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
     <link href="/static/css/justified-nav.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

<body >
<div>
      <a href="/logout/" class="btn btn-info btn-lg pull-right" style="margin:0 0 10px 10px;" >
          <span class="glyphicon glyphicon-log-out"></span> Log out
        </a>
</div>

<div class="container">

            <p>Create User Details</p>
              <div class ="col-md-4">

               <div class ="col-md-4">
                {% if  success %}
                 <div class="alert alert-success" role="alert"><b>Success</b> : message</div>
                 {% else %}
                 {{form.errors}}
                 {% endif %}

              </div>
                <div class ="col-md-4">

            <form class="m-t" role="form"  method="POST" action="">
        {%csrf_token%}
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Name"  maxlength="30" name="username" type="text" required="">
                </div>
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Email" name="email" required="">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password" name="password" required="">
                </div>
                <button style="background-color: #1ab394;  width: 100%;  border-radius: 10px;  padding: 8px 0px 8px 0px; color:#fff;" value="Register">Register</button>

            </form>
                </div>
                 <div class ="col-md-4">
                 <a href="/profile/">back</a>
                 
  
                  </div>

    
        </div>

    <!-- Mainly scripts -->
    <script src="js/jquery-2.1.1.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="js/plugins/iCheck/icheck.min.js"></script>

</body>

</html>
 

operatoradmin/templates/backup_vendor.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Phone-o-friend</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/font-awesome.css" rel="stylesheet">
     <link href="/static/css/plugins/iCheck/custom.css" rel="stylesheet">
     <link href="/static/css/ampm.css"  rel="stylesheet">


    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
     <link href="/static/css/justified-nav.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
    <div class ="img">
</div>


      <!-- The justified navigation menu is meant for single line per list item.
           Multiple lines will require custom code not provided by Bootstrap. -->
      <div class="masthead">


<body class="gray-bg">

    <div class="middle-box text-center loginscreen animated fadeInDown login-top">
        <div>
            <div>


            </div>
            <p>wlecome to phone-o-friend app </p>
            <p>{{request.user.username}}
             <div class ="col-md-4">
            </div>
            <div class ="col-md-4">
            <form class="m-t" role="form" action="/vendor/" method="POST">{% csrf_token %}
                <div class="form-group">
                  <div class="dropdown dropdown-select">
                  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                    Dropdown
                   <span class="caret"></span>
                    </button>
                     <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                  {% for  category in category_list %}
                  <li>{{ category.category_name }}</li>
                  {%endfor%}
                  </ul>
                   </div>
      
    </div>


                                  <!--<font color="red">Please Enter Valid Credentials...</font></br>-->


            </form>
             </div>
             <div  class ="col-md-4">
             </div>
        </div>
    </div>
<script>
	$('.dropdown-select').on( 'click', '.dropdown-menu li a', function() { 
	   var target = $(this).html();

	   //Adds active class to selected item
	   $(this).parents('.dropdown-menu').find('li').removeClass('active');
	   $(this).parent('li').addClass('active');

	   //Displays selected text on dropdown-toggle button
	   $(this).parents('.dropdown-select').find('.dropdown-toggle').html(target + ' <span class="caret"></span>');
	})
</script>
    <!-- Mainly scripts -->
    <script src="js/jquery-2.1.1.js"></script>
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

operatoradmin/templates/list.html
i{% for contact in contacts %}
    {# Each "contact" is a Contact model object. #}
    {{ contact.username }}<br />
    ...
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if contacts.has_previous %}
            <a href="?page={{ contacts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
        </span>

        {% if contacts.has_next %}
            <a href="?page={{ contacts.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

operatoradmin/templates/product_add_info.html
<p> SUCCESSFULLY ADDED PRODUCT</p>

<a  href="/vendor/"> back </a>

operatoradmin/templates/show.html
<html>

<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("#hide").click(function(){
        $("p").hide();
    });
    $("#show").click(function(){
        $("p").show();
    });
});
</script>
</head>

<body>
<p>
{% for i in result %}

{{i.username}}
{% endfor %}</p>


<button id="hide">Hide</button>
<button id="show">Show</button>

operatoradmin/templates/success.html
<html>
<body>
<p> <font color="green">SUCCESSFULLY USER CRETAED</font></p>
<div>
      <a href="/adduser/" class="btn btn-info btn-lg pull-right" style="margin:0 0 10px 10px;" >
          <span class="glyphicon glyphicon-log-out"></span>back 
        </a>
      <a href="/profile/" class="btn btn-info btn-lg pull-right" style="margin:0 0 10px 10px;" >
          <span class="glyphicon glyphicon-log-out"></span>Profile
        </a>

</div>

operatoradmin/templates/vendor.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Phone-o-friend</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/font-awesome.css" rel="stylesheet">
     <link href="/static/css/plugins/iCheck/custom.css" rel="stylesheet">
     <link href="/static/css/ampm.css"  rel="stylesheet">


    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
     <link href="/static/css/justified-nav.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
<p><span style="float: right;color:#fff;color:green;" >Hi Welcome to {{request.user.username}}</span>
<div>
      <a href="/logout/" class="btn btn-info btn-lg pull-right" style="margin:0 0 10px 10px;" >
          <span class="glyphicon glyphicon-log-out"></span> Log out

        </a>
</div>
<div style="display:block; clear: both;" >
      <a href="/get_product_list/" class="btn btn-info btn-lg pull-left" style="margin:0 0 10px 10px;" >
          <span class="glyphicon glyphicon-backward"></span> Product List
        </a>
</div>
<div style="display:block;clear: both;">
      <a href="/changepassword/" class="btn btn-info btn-lg pull-left" style="margin:0 0 10px 10px;" >
          <span class="glyphicon glyphicon-pencil"></span> Change Password
        </a>

</div>
</div>

</div>


      <!-- The justified navigation menu is meant for single line per list item.
           Multiple lines will require custom code not provided by Bootstrap. -->
      <div class="masthead">


<body class="gray-bg">

    <div class="middle-box text-center loginscreen animated fadeInDown login-top">
        <div>
            <div>

            </div>
            <p>wlecome to phone-o-friend app </p>
            <p>{{request.user.username}}
            <form id="bootstrapSelectForm" method="post" class="form-horizontal" action="/vendor/" enctype="multipart/form-data"> 
              {%csrf_token%}
                {% if form.errors%}
		   <font color="red">* All fields are mandatory</font></br>
		{% endif %}
                {{ form.as_p }}
 <div class="form-group">

                </div>

 <button style="background-color: #1ab394;  width: 100%;  border-radius: 10px;  padding: 8px 0px 8px 0px; color:#fff;" value="submit">Submit</button>

</form>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script>

$(document).ready(function () {
  //your code here

  $('#id_category_name').change(function(){
     var val = $(this).val();
     request_url = "/category_id/"+val+"/"
     $('#id_subcategory_name').empty();
     $('#id_subcategory_name').append('<option value="">select</option>');
     $.ajax({
       url: request_url,
       success: function(data){
          $.each(data,function(key,value){
              $('#id_subcategory_name').append('<option value="'+ key +'">'+ value +'</option>');
          });
       }
  });
  });
  $('#id_subcategory_name').change(function(){
     var val = $(this).val();
     request_url = "/subcategory_id/"+val+"/"
     $('#id_brand_name').empty();
     $('#id_brand_name').append('<option value="">select</option>');
     $.ajax({
       url: request_url,
       success: function(data){
          $.each(data,function(key,value){
              $('#id_brand_name').append('<option value="'+ key +'">'+ value +'</option>');
          });
       }
  });
  });

});
</script>
    <!-- Mainly scripts 
    <script src="js/jquery-2.1.1.js"></script>
    <script src="js/bootstrap.min.js"></script> -->

</body>

</html>